### ISSUE TITLE
Call to member function on non-object

### ISSUE THREAD

**Issue by rmcgirr83** [themejunkie/delivery-lite#1]
https://github.com/themejunkie/delivery-lite/blob/master/inc/template-tags.php#L196

is causing an error

Fatal error: Call to a member function have_posts() on a non-object

when upgrading to latest version from wordpress.

**Comment by gasatrya** [comment]
Hmm.. that's weird. Have you tried to deactivated all plugins?

**Comment by rmcgirr83** [comment]
Not sure what the problem was but it seems to have magically fixed itself.
